version: '3'

services:
###> doctrine/doctrine-bundle ###
  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
  
  app:
    container_name: app
    image: 10f0c2fe89067c91af5676e432fc22a259a84e4815efa10363c8a30455890be7
    ports:
      - '8000:80'