version: '3'

services:
  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    networks:
      - app_network
  
  app:
    container_name: app-microservice
    image: 36dec4d66e35b3443398747bc864d66be2632b6601fb3aa2a28314d9360451e4 
    ports:
      - '8000:80'
    volumes:
      - .:/var/www
    networks:
      - app_network

networks:
  app_network:
    external: true