version: '3'

services:
  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    networks:
      - app_network
  
  app:
    container_name: app-microservice
    image: sha256:c7cefb6d6adc4351a61039bd8b12050d40b7fbfc65867c8c4098f863cb181439
    ports:
      - '8000:80'
    volumes:
      - .:/var/www
    networks:
      - app_network

networks:
  app_network:
    external: true