version: '3'

services:
###> doctrine/doctrine-bundle ###
  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
  
  app:
    container_name: app-microservice
    image: db8412534291402e47f6cf5ff1854927462d2550f8f7e99df0f7af3a129e749d
    ports:
      - '8000:80'